sudo: false
language: python
cache:
  directories:
    - $HOME/.cache/pip

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - env: TOXENV=py37
      python: nightly
  allow_failures:
    - python: nightly

install:
    - pip install -U tox nose cython

script:
    - tox -e $TOXENV
